---
# Ansible Galaxy requirements file
# Install with: ansible-galaxy install -r requirements.yml

roles: []
  # Example external role dependencies:
  # - name: geerlingguy.security
  #   version: ">=1.0.0"

collections:
  - name: community.general
    version: ">=6.0.0"
  - name: ansible.posix
    version: ">=1.4.0"
