---
- name: "Manage global user's group"
  group:
    name: "{{ users_default_group }}"
    state: present
  when:
    - not users_create_group_per_user

- name: "Manage per-user groups"
  group:
    name: "{{ item.0.username }}"
    gid: "{{ item.0.uid | default(omit) }}"
    state: "{{ item.0.state }}"
  with_subelements:
    - "{{ users }}"
    - target_hosts
    - skip_missing: True
  when:
    - users is iterable and users_create_group_per_user
    - item.0.state == 'present'
    - inventory_hostname in groups[item.1] or item.1 == 'all'

- name: "Manage groups"
  group:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ users_group_list }}"
  when:
    - users_group_list is iterable
    
- name: "Manage user accounts"
  user:
    name: "{{ item.0.username }}"
    uid: "{{ item.0.uid | default(omit) }}"
    group: "{{ item.0.username if users_create_group_per_user else users_default_group }}"
    groups: "{{ item.0.groups | default(omit) }}"
    shell: "{{ item.0.shell | default(users_default_shell) }}"
    createhome: "{{ 'yes' if users_create_homedir else 'no' }}"
    home: "{{ item.0.home | default('/home/%s' % item.0.username) }}"
    system: "{{ item.0.system | default('no')  }}"
    password: "{{ item.0.password | default(omit) }}"
    generate_ssh_key: "{{ item.0.generate_key | default('no') }}"
    ssh_key_comment: "{{ item.0.username }}@{{ ansible_hostname }}"
    comment: "{{ item.0.name | default('') }}"
    state: "{{ item.0.state }}"
  with_subelements:
    - "{{ users }}"
    - target_hosts
    - skip_missing: True
  when:
    - users is iterable
    - inventory_hostname in groups[item.1] or item.1 == 'all'

- name: "Manage users SSH keys"
  authorized_key:
    user: "{{ item.0.username }}"
    key: "{{ item.0.authorized | list | join('\n') }}"
    exclusive: "{{ item.0.exclusive | default('no') }}"
  with_subelements:
    - "{{ users }}"
    - target_hosts
    - skip_missing: True
  when:
    - users is iterable
    - inventory_hostname in groups[item.1] or item.1 == 'all'
    - item.0.state == 'present'

- name: "Secure the users SSH directory"
  file:
    dest: "{{ item.0.home if item.0.home is defined else '/home/%s' % item.0.username }}/.ssh"
    state: directory
    mode: 0700
  with_subelements:
    - "{{ users }}"
    - target_hosts
    - skip_missing: True
  when:
    - users is iterable
    - inventory_hostname in groups[item.1] or item.1 == 'all'
    - item.0.state == 'present'

- name: "Ensure directory ownership"
  file:
    path: "{{ item.0.home if item.0.home is defined else '/home/%s' % item.0.username }}"
    state: directory
    owner: "{{ item.0.username }}"
    group: "{{ item.0.username if users_create_group_per_user else users_default_group }}"
    recurse: yes
  with_subelements:
    - "{{ users }}"
    - target_hosts
    - skip_missing: True
  when:
    - users is iterable
    - users_create_homedir
    - item.0.state == 'present'
    - inventory_hostname in groups[item.1] or item.1 == 'all'

- name: "Clean up deleted user group"
  group:
    name: "{{ item.0.username }}"
    gid: "{{ item.0.uid | default(omit) }}"
    state: "{{ item.0.state }}"
  with_subelements:
    - "{{ users }}"
    - target_hosts
    - skip_missing: True
  when:
    - users is iterable and users_create_group_per_user
    - item.0.state == 'absent'
    - inventory_hostname in groups[item.1] or item.1 == 'all'

- name: "Clean up deleted user directory"
  file:
    path: "{{ item.0.home if item.0.home is defined else '/home/%s' % item.0.username }}"
    state: "{{ item.0.state }}"
  with_subelements:
    - "{{ users }}"
    - target_hosts
    - skip_missing: True
  when:
    - users is iterable and users_create_group_per_user
    - item.0.state == 'absent'
    - inventory_hostname in groups[item.1] or item.1 == 'all'
    - delete_homedirs