---
- name: "Determine target hosts"
  set_fact:
     do_run: True
  with_subelements:
    - "{{ users }}"
    - target_hosts
    - skip_missing: True
  when:
    - item.1 in group_names

- name: "Manage global user's group"
  group:
    name: "{{ users_default_group }}"
    state: present
  when:
    - not users_create_group_per_user

- name: "Manage per-user groups"
  group:
    name: "{{ item.username }}"
    gid: "{{ item.uid | default(omit) }}"
    state: "{{ item.state }}"
  loop: "{{ users }}"
  when:
    - users is iterable and users_create_group_per_user
    - do_run is defined or item.target_hosts is not defined

- name: "Manage groups"
  group:
    name: "{{ item }}"
    state: "{{ item.state | default('present') }}"
  loop:
    - "{{ users_group_list }}"
  when:
    - users_group_list is iterable
    
- name: "Manage user accounts"
  user:
    name: "{{ item.username }}"
    uid: "{{ item.uid | default(omit) }}"
    group: "{{ item.username if users_create_group_per_user else users_default_group }}"
    groups: "{{ item.groups|join(',') | default('') }}"
    shell: "{{ item.shell | default(users_default_shell) }}"
    createhome: "{{ 'yes' if users_create_homedir else 'no' }}"
    home: "{{ item.home | default('/home/%s' % item.username) }}"
    system: "{{ item.system | default('no')  }}"
    password: "{{ item.password | default(omit) }}"
    generate_ssh_key: "{{ item.generate_key | default('no') }}"
    ssh_key_comment: "{{ item.username }}@{{ ansible_hostname }}"
    comment: "{{ item.name | default('') }}"
    state: "{{ item.state }}"
  loop: "{{ users }}"
  when:
    - users is iterable
    - do_run is defined or item.target_hosts is not defined

- name: "Manage users SSH keys"
  authorized_key:
    user: "{{ item.0.username }}"
    key: "{{ item.1 }}"
    exclusive: "{{ item.0.exclusive | default('no') }}"
  with_subelements:
    - "{{ users }}"
    - authorized
  when:
    - users is iterable
    - do_run is defined or item.0.target_hosts is not defined
    - item.0.state == 'present'

- name: "Manage user's SSH keys only"
  authorized_key:
    user: "{{ item.0.username }}"
    key: "{{ item.1 }}"
    state: 'present'
    exclusive: "{{ item.0.exclusive | default('no') }}"
  with_subelements:
    - "{{ users_keys }}"
    - authorized
  when:
    - users_keys is iterable
    - do_run is defined or item.0.target_hosts is not defined

- name: "Secure the users SSH directory"
  file:
    dest: "{{ item.home if item.home is defined else '/home/%s' % item.username }}/.ssh"
    state: directory
    mode: 0700
  loop: "{{ users }}"
  when:
    - users is iterable
    - do_run is defined or item.target_hosts is not defined
    - item.state == 'present'
